### ISSUE TITLE
lazyXDS: why need create envoyfilter for every service and file size is too large

### ISSUE THREAD

**Issue by stanxing** [aeraki-framework/aeraki#115]
**Is your feature request related to a problem? Please describe.**

Every service will be created a EnvoyFilter resource, the EnvoyFilter contains all the services needing redirect to global sidecar and file is too large if have many services. 

Rules are configured for each service, is there a performance problem(in match stage OR xds merge stage)? 

I know the EnvoyFilter will add header `lazyxds-service-address` before forwarding the service and egress will route according to this header.  Why not let egress cache all the configurations to avoid this route?

I'm not an expert in istio, maybe I don't think carefully in many places, thank you for answering my questions.

**Comment by zhongfox** [comment]
hi @stanxing, the key reason is we don't want forward all service to lazy-egress, such as:
1. access service which is out of mesh, like google.com.
2. access tcp service, which currently we not support lazy-loading.
so we need put all http services into envoyfilter. 
feel free to ask anything :)

**Comment by FeiYing9** [comment]
初始创建的Sidecar资源中，`egress.hosts`里是不是除了`istio-system/*`之外，还把svc中端口中[非http](https://github.com/aeraki-framework/aeraki/blob/bd9d91d52b0acd5773f27ad356af7eb3eaf1a6f1/lazyxds/pkg/utils/protocal.go#L24)的svc也都添加进去了呢？

因为刚测试了一下，发现除了`istio-system/*`还有好多其他svc的全域名
