### ISSUE TITLE
[question] support  more traffic management

### ISSUE THREAD

**Issue by shuxnhs** [aeraki-framework/aeraki#59]
Can we use istio+aeraki to do more traffic management our dubbo services, such as circuit break, timeout, retry etc

**Comment by zhaohuabing** [comment]
Basically, we can add whatever Envoy dubbo proxy allows us to do in the control plane with the help of Aeraki. If there're features we want to achieve but dubbo proxy doesn't support yet, we need to implement it at the dubbo proxy side first.
