### ISSUE TITLE
关于懒加载对于ServiceEntry的处理

### ISSUE THREAD

**Issue by jjy96** [aeraki-framework/aeraki#81]
目前代码里面看到对于ServiceEntry是全量下发给所有的Sidecar，这个是出于什么考虑呢？我们公司目前的做法是以ServiceEntry为主，Service几乎没有，这种场景下面，我们相当于还是全量下发配置了，后续是否会考虑增加针对ServiceEntry的懒加载

![image](https://user-images.githubusercontent.com/38353946/124057945-fe1a9980-da5a-11eb-9fb2-fe3aa2320c46.png)

![image](https://user-images.githubusercontent.com/38353946/124057968-08d52e80-da5b-11eb-94a7-0422c0c0dde1.png)

**Comment by zhongfox** [comment]
This is in our todo list, currently we have not handle lazy xds of service entry.
contribution is welcome. @jjy96

**Comment by jjy96** [comment]
> This is in our todo list, currently we have not handle lazy xds of service entry.
> contribution is welcome. @jjy96

i will if i can, and thx for answer
